server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yagi
    username: root
    password: "0412"
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        format_sql: true
    generate-ddl: true
